version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - libgsl27
    - libgsl-dev
    - libgslcblas0

python:
  install:
    - requirements: docs/readthedocs-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
