version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - libgsl27
    - libgsl-dev
    - libgslcblas0
  jobs:
    post_install:
      - python3 -c 'import mskpy.config'
      - cat ~/.config/mskpy/mskpy.cfg


python:
  install:
    - requirements: docs/readthedocs-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
